name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    environment: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install pm2
        run: npm install pm2

      - name: Set up SSH
        run: |
          mkdir -p $HOME/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./$DEPLOY_KEY
          sudo chmod 600 ./$DEPLOY_KEY
          echo "$SSH_KNOWN_HOSTS" > $HOME/.ssh/known_hosts
        shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy
        run: npm run deploy:prod
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
